version: 2

jobs:
  audit:
    docker:
      - image: &node_image circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Audit
          command: |
            yarn -v
            yarn audit

  publish:
    docker:
      - image: *node_image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - deploy:
          name: Publish
          when: on_success
          command: |
            git config --global user.name Bot Vance
            git config --global user.email bot@autovance.com
            npx semantic-release --ci

workflows:
  version: 2
  audit:
    jobs:
      - audit:
          context: org-global

  publish:
    jobs:
      - publish:
          context: deploy-npm
          filters:
            branches:
              only: main
